name : "Pehla Workflow on Github Action"

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs: 
  terraform-job:
   environment: dev
   runs-on: self-hosted
   steps:
        - name: Checkout
          uses: actions/checkout@v5.0.0

        - name: Install Terraform
          uses: little-core-labs/install-terraform@v2.0.0
          with:
            version: 1.13.0
          
        - name: Azure Login
          uses: Azure/login@v2.3.0
          with:
            client-id: cf054bd2-cdd3-4b1e-a48a-6c5468184b2f
            tenant-id: d49a6a04-c150-412a-af23-dc2fcc908e3c
            subscription-id: 99c7c7ea-a267-488b-9d38-a2547f06712c

        
        - name: Terraform Init
          id: init
          run: terraform init -input=false
          working-directory: environments/dev

        - name: Terraform fmt
          id: fmt
          run: terraform fmt -check
          continue-on-error: true
          working-directory: environments/dev

        - name: Terraform Validate
          id: validate
          run: terraform validate -no-color
          working-directory: environments/dev
        
        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color -input=false
          continue-on-error: true
          working-directory: environments/dev

          
        # - name: Manual Workflow Approval
        #   uses: trstringer/manual-approval@v1.9.0
        #   # with:
        #     # # Required approvers
        #     # approvers: 
        #     # # Secret
        #     # secret: 
        #     # # Minimum number of approvals to progress workflow
        #     # minimum-approvals: # optional
        #     # # The custom subtitle for the issue
        #     # issue-title: # optional
        #     # # The custom body for the issue
        #     # issue-body: # optional
        #     # # Whether or not to filter out the user who initiated the workflow as an approver if they are in the approvers list
        #     # exclude-workflow-initiator-as-approver: # optional
        #     # # Comma separated list of words that can be used to approve beyond the defaults.
        #     # additional-approved-words: # optional, default is 
        #     # # Comma separated list of words that can be used to deny beyond the defaults.
        #     # additional-denied-words: # optional, default is 
                  







            
            
          
