name : "Pehla Workflow on Github Action"

on: workflow_dispatch

jobs: 
  terraform-job:
    runs_on: self-hosted
       steps:
          - name: Checkout
            uses: actions/checkout@v5.0.0
  
