name : "Pehla Workflow on Github Action"

on: workflow_dispatch

permissions:
  id-token: write
  contents: read

jobs: 
  terraform-init-plan:
   environment: dev
   runs-on: self-hosted
   steps:
        - name: Checkout
          uses: actions/checkout@v5.0.0

        - name: Install Terraform
          uses: little-core-labs/install-terraform@v2.0.0
          with:
            version: 1.13.0
          
        - name: Azure Login
          uses: Azure/login@v2.3.0
          with:
            client-id: cf054bd2-cdd3-4b1e-a48a-6c5468184b2f
            tenant-id: d49a6a04-c150-412a-af23-dc2fcc908e3c
            subscription-id: 99c7c7ea-a267-488b-9d38-a2547f06712c

        
        - name: Terraform Init
          id: init
          run: terraform init -input=false
          working-directory: environments/dev


        - name: Terraform Validate
          id: validate
          run: terraform validate -no-color
          working-directory: environments/dev
        
        - name: Terraform Plan
          id: plan
          run: terraform plan -no-color -input=false
          continue-on-error: true
          working-directory: environments/dev

  terraform-apply:
   environment: dev
   needs:  terraform-init-plan
   runs-on: self-hosted
   steps:
        - name: Checkout
          uses: actions/checkout@v5.0.0

        - name: Azure Login
          uses: Azure/login@v2.3.0
          with:
            client-id: cf054bd2-cdd3-4b1e-a48a-6c5468184b2f
            tenant-id: d49a6a04-c150-412a-af23-dc2fcc908e3c
            subscription-id: 99c7c7ea-a267-488b-9d38-a2547f06712c

        - name: Terraform Init
          run: terraform init -input=false
          working-directory: environments/dev

        - name: Terraform Apply
          run: terraform apply -auto-approve -input=false
          working-directory: environments/dev




            


          

          
        # 
